// <auto-generated />
using System;
using CarpetProgressTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarpetProgressTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203035201_InitialProject")]
    partial class InitialProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarpetProgressTracker.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("base_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("current_image_url");

                    b.Property<decimal>("CurrentProgress")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("current_progress");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<string>("ProgressMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("progress_mode");

                    b.Property<int>("StandardHeight")
                        .HasColumnType("integer")
                        .HasColumnName("standard_height");

                    b.Property<int>("StandardWidth")
                        .HasColumnType("integer")
                        .HasColumnName("standard_width");

                    b.Property<int>("TotalPixels")
                        .HasColumnType("integer")
                        .HasColumnName("total_pixels");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("orders");
                });

            modelBuilder.Entity("CarpetProgressTracker.Models.ProgressHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("progress_percentage");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderNumber");

                    b.ToTable("progress_history");
                });

            modelBuilder.Entity("CarpetProgressTracker.Models.ProgressHistory", b =>
                {
                    b.HasOne("CarpetProgressTracker.Models.Order", "Order")
                        .WithMany("ProgressHistories")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CarpetProgressTracker.Models.Order", b =>
                {
                    b.Navigation("ProgressHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
